version: '3.8'

services:
  backend:
    build:
      context: ./server/AI
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./server/AI:/app/server/AI
    command: ["/opt/venv/bin/uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app/frontend