FROM node:14

# Set up the frontend
WORKDIR /app/frontend
COPY frontend /app/frontend

# Install Node.js dependencies and build the frontend
RUN npm install
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]